---
- hosts: apigee
  vars:
    apigee_license_file_name: license.txt
    apigee_source_path: ../config
    apigee_dest_path: /tmp/apigee
    apigee_config_file_name: config.txt
    apigee_prod_config_file_name: setup-org-prod.txt
    apigee_test_config_file_name: setup-org-test.txt
  tasks:
  - name: copy license file
    copy: src={{apigee_source_path}}/{{apigee_license_file_name}}
        dest={{apigee_dest_path}}/{{apigee_license_file_name}} force=yes
    sudo: yes
  - name: copy config file
    copy: src={{apigee_source_path}}/{{apigee_config_file_name}}
        dest={{apigee_dest_path}}/{{apigee_config_file_name}} force=yes
    sudo: yes
  - name: copy setup-org prod file
    copy: src={{apigee_source_path}}/{{apigee_prod_config_file_name}}
        dest={{apigee_dest_path}}/{{apigee_prod_config_file_name}} force=yes
    sudo: yes
  - name: copy setup-org test file
    copy: src={{apigee_source_path}}/{{apigee_test_config_file_name}}
        dest={{apigee_dest_path}}/{{apigee_test_config_file_name}} force=yes
    sudo: yes
- include: ds-playbook.yaml
- include: ms-playbook.yaml
- include: rmp-playbook.yaml
- include: qs-playbook.yaml
- include: ps-playbook.yaml
- include: orgsetup-playbook.yaml

