---
- hosts: qs
  vars:
    apigee_source_path: ../config
    apigee_dest_path: /tmp
    apigee_config_file_name: config.txt
  tasks:
  - name: Run Setup to install QPID Server
    command: "/opt/apigee/apigee-setup/bin/setup.sh -p qs -f {{apigee_dest_path}}/{{apigee_config_file_name}}"
    sudo: yes
